"""
SQLAlchemy models base and storage conventions.

This module establishes the declarative base and storage conventions
for the Agentic Job Matching System database models, complying with
SQLAlchemy 2.x conventions and SQLite storage guidelines.
"""

from datetime import datetime, timezone
import uuid
from typing import Annotated

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text, Index, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    SQLAlchemy Declarative Base using SQLAlchemy 2.x conventions.
    All database models will inherit from this base class.
    """
    pass


def generate_uuid() -> str:
    """
    Generate a canonical UUID4 string.
    
    Used as the default generator for UUID-based string primary keys.
    """
    return str(uuid.uuid4())


def utc_now() -> datetime:
    """
    Generate a UTC datetime object with timezone offset.
    
    Used as the default generator for consistently stored timestamps.
    """
    return datetime.now(timezone.utc)


# Storage Conventions (Reusable Annotations for model columns)

# UUID Primary Key: TEXT canonical UUID string, autogenerated by default
uuid_pk = Annotated[
    str,
    mapped_column(
        String(36),
        primary_key=True,
        default=generate_uuid,
        doc="Canonical UUID string primary key"
    )
]

# Timestamps: Consistent SQLAlchemy DateTime stored as timezone-aware UTC datetime.
created_timestamp = Annotated[
    datetime,
    mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
        doc="Record creation timestamp (UTC)"
    )
]

updated_timestamp = Annotated[
    datetime,
    mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        onupdate=utc_now,
        nullable=False,
        doc="Record update timestamp (UTC)"
    )
]


class RoleProfile(Base):
    """
    RoleProfile ORM model representing user's target job role and preferences.
    """
    __tablename__ = "role_profiles"

    id: Mapped[uuid_pk]
    target_role: Mapped[str] = mapped_column(Text, nullable=False, doc="Target job role")
    level: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Experience level (intern, fresher, junior)")
    location: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Desired location")
    accept_remote: Mapped[bool | None] = mapped_column(Boolean, nullable=True, doc="Whether remote jobs are acceptable")
    skills: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Desired canonical skills as a JSON array")
    resume_text: Mapped[str | None] = mapped_column(Text, nullable=True, doc="CV/Profile raw text")
    created_at: Mapped[created_timestamp]
    updated_at: Mapped[updated_timestamp]


class JobPost(Base):
    """
    JobPost ORM model representing a retrieved job listing and its processing metadata.
    """
    __tablename__ = "job_posts"

    __table_args__ = (
        Index("idx_job_posts_status", "status"),
        Index("idx_job_posts_final_score", text("final_score DESC")),
        Index("idx_job_posts_jd_status", "jd_status"),
        Index("idx_job_posts_batch_id", "batch_id"),
        Index("idx_job_posts_role_profile_status_score", "role_profile_id", "status", text("final_score DESC")),
        Index(
            "idx_job_posts_raw_content_hash",
            "raw_content_hash",
            unique=True,
            sqlite_where=text("raw_content_hash IS NOT NULL")
        ),
        Index("idx_job_posts_dedup_key", "dedup_key"),
    )

    id: Mapped[uuid_pk]
    batch_id: Mapped[str] = mapped_column(
        String(36),
        nullable=False,
        default=generate_uuid,
        doc="Search/import batch ID as UUID string"
    )
    role_profile_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("role_profiles.id"),
        nullable=False,
        doc="Profile ID as UUID string (Foreign Key)"
    )
    title: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Job title")
    company: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Company")
    location: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Location")
    work_mode: Mapped[str | None] = mapped_column(Text, nullable=True, doc="onsite/remote/hybrid/unknown")
    level: Mapped[str | None] = mapped_column(Text, nullable=True, doc="intern/fresher/junior/mid/senior/unknown")
    employment_type: Mapped[str | None] = mapped_column(Text, nullable=True, doc="internship/full-time/part-time/contract/unknown")
    salary: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Salary if specified")
    responsibilities: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Responsibilities")
    requirements: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Requirements")
    skills: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Extracted canonical skills as a JSON array")
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Source URL if available")
    source_platform: Mapped[str | None] = mapped_column(Text, nullable=True, doc="tavily/manual_url/manual_text/job_board")
    parse_status: Mapped[str | None] = mapped_column(Text, nullable=True, doc="success/needs_manual_input/failed")
    raw_content_hash: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Hash of cleaned raw content")
    dedup_key: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Hash of company + title")
    duplicate_of_job_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("job_posts.id"),
        nullable=True,
        doc="Original job ID as UUID string if duplicate (self-reference)"
    )
    jd_status: Mapped[str | None] = mapped_column(Text, nullable=True, doc="full_jd/partial_jd/contact_for_jd/no_jd/unclear")
    extraction_status: Mapped[str | None] = mapped_column(Text, nullable=True, doc="success/retried/failed")
    error_reason: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Error details if applicable")
    should_score_similarity: Mapped[bool | None] = mapped_column(Boolean, nullable=True, doc="Whether scoring is allowed")
    embedding_text: Mapped[str | None] = mapped_column(Text, nullable=True, doc="Cleaned text used for embedding")
    embedding_similarity: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Normalized semantic similarity")
    skill_overlap_score: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Normalized skill overlap")
    location_match_score: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Normalized location score")
    level_match_score: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Normalized level score")
    base_score: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Score before JD confidence multiplier")
    jd_confidence_multiplier: Mapped[float | None] = mapped_column(Float, nullable=True, doc="JD confidence multiplier")
    final_score: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Final score [0, 1]")
    final_score_percent: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Final score out of 100")
    status: Mapped[str | None] = mapped_column(Text, nullable=True, doc="pending_review/saved/applied/interview/rejected/offer/ignored")
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True, doc="LLM input tokens")
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True, doc="LLM output tokens")
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True, doc="Estimated API cost")
    extraction_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True, doc="Optional extraction time")
    discovered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="Discovered timestamp (UTC)"
    )
    created_at: Mapped[created_timestamp]
    updated_at: Mapped[updated_timestamp]


class Application(Base):
    """
    Application ORM model representing job application status and details.

    Explicit Delete Behavior:
    We use ON DELETE CASCADE on the job_post_id foreign key. When a job post is deleted,
    SQLite will automatically delete any matching application tracking records, ensuring
    database consistency and safety.

    Allowed Statuses:
    Must align with app.core.constants.APPLICATION_STATUSES:
    'applied', 'interview', 'rejected', 'offer'.
    """
    __tablename__ = "applications"

    __table_args__ = (
        Index("idx_applications_job_post_id", "job_post_id"),
    )

    id: Mapped[uuid_pk]
    job_post_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("job_posts.id", ondelete="CASCADE"),
        nullable=False,
        doc="Job Post ID as UUID string (Foreign Key with explicit ON DELETE CASCADE)"
    )
    status: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Application status (applied/interview/rejected/offer)"
    )
    cv_version: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="CV version used for the application"
    )
    notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Notes/details about the application"
    )
    applied_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="Application timestamp (UTC)"
    )
    updated_at: Mapped[updated_timestamp]


class ChatConversation(Base):
    """Persisted chat session scoped to one role profile."""
    __tablename__ = "chat_conversations"

    __table_args__ = (
        Index("idx_chat_conversations_role_profile_updated", "role_profile_id", text("updated_at DESC")),
    )

    id: Mapped[uuid_pk]
    role_profile_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("role_profiles.id"),
        nullable=False,
    )
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="active")
    created_at: Mapped[created_timestamp]
    updated_at: Mapped[updated_timestamp]


class ChatMessage(Base):
    """Full persisted chat message history. Working memory is bounded separately."""
    __tablename__ = "chat_messages"

    __table_args__ = (
        Index("idx_chat_messages_conversation_created", "conversation_id", "created_at"),
    )

    id: Mapped[uuid_pk]
    conversation_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("chat_conversations.id", ondelete="CASCADE"),
        nullable=False,
    )
    role: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    token_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    metadata_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[created_timestamp]


class AgentToolCall(Base):
    """Sanitized visible tool call event persisted for chat UI."""
    __tablename__ = "agent_tool_calls"

    __table_args__ = (
        Index("idx_agent_tool_calls_conversation_created", "conversation_id", "created_at"),
    )

    id: Mapped[uuid_pk]
    conversation_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("chat_conversations.id", ondelete="CASCADE"),
        nullable=False,
    )
    assistant_message_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("chat_messages.id", ondelete="SET NULL"),
        nullable=True,
    )
    tool_name: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="pending")
    input_summary: Mapped[str] = mapped_column(Text, nullable=False)
    result_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    safe_payload_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[created_timestamp]
    updated_at: Mapped[updated_timestamp]
